from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel, Field
from typing import List, Optional
import uuid

from app import config
from app.database import (
    save_evaluation_run,
    get_all_runs,
    get_run_by_id,
    get_comparison_report,
    get_quota_statistics
)
from app.judge import evaluate_sample, QUOTA_USAGE

router = APIRouter()

# Pydantic Schemas for requests and responses
class SampleInput(BaseModel):
    id: Optional[str] = Field(None, description="Optional unique identifier for the sample")
    question: str = Field(..., description="The query submitted to the RAG pipeline")
    retrieved_context: str = Field(..., description="Context chunks retrieved by the RAG system")
    model_output: str = Field(..., description="Answer generated by the pipeline's LLM")
    ground_truth: Optional[str] = Field(None, description="Optional golden answer for comparison")

class EvaluateRequest(BaseModel):
    pipeline_version: str = Field(..., description="Version identifier of the pipeline being evaluated (e.g. v1.0.0)")
    samples: List[SampleInput] = Field(..., description="List of samples to evaluate")
    provider: Optional[str] = Field(None, description="Judge provider (GEMINI or OLLAMA). Defaults to server config.")

class EvaluateResponse(BaseModel):
    run_id: str
    pipeline_version: str
    sample_count: int
    message: str

@router.post("/evaluate", response_model=EvaluateResponse)
async def evaluate_batch(request: EvaluateRequest, limit: Optional[int] = Query(None, alias="sample-limit")):
    """
    Evaluates a batch of RAG samples. Runs them through faithfulness, relevance, clarity 
    rubrics, calculates cosine similarities, caches results, and records the run in the database.
    """
    if not request.pipeline_version:
        raise HTTPException(status_code=400, detail="pipeline_version is required.")
    
    if not request.samples:
        raise HTTPException(status_code=400, detail="samples list cannot be empty.")
    
    # Cap samples if limit is specified
    samples_to_eval = request.samples
    if limit is not None and limit > 0:
        samples_to_eval = request.samples[:limit]

    evaluated_samples = []
    
    for s in samples_to_eval:
        try:
            # Run evaluations. If pre-seeded, this will HIT the cache instantly.
            eval_result = evaluate_sample(
                question=s.question,
                context=s.retrieved_context,
                output=s.model_output,
                provider=request.provider
            )
            
            evaluated_samples.append({
                "id": s.id or f"sample_{uuid.uuid4().hex[:8]}",
                "question": s.question,
                "retrieved_context": s.retrieved_context,
                "model_output": s.model_output,
                "ground_truth": s.ground_truth,
                "evaluation": eval_result
            })
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Failed during evaluation of sample: {str(e)}")

    try:
        # Save run summary & detailed scores in SQLite
        run_id = save_evaluation_run(request.pipeline_version, evaluated_samples)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to save evaluation run: {str(e)}")

    return EvaluateResponse(
        run_id=run_id,
        pipeline_version=request.pipeline_version,
        sample_count=len(evaluated_samples),
        message="Evaluation run completed and saved successfully."
    )

@router.get("/runs")
async def list_runs():
    """Fetches all completed evaluation runs sorted by latest date."""
    try:
        return get_all_runs()
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/runs/{run_id}")
async def get_run_details(run_id: str):
    """Fetches detailed scores and judge reasoning for a specific run."""
    try:
        run_details = get_run_by_id(run_id)
        if not run_details:
            raise HTTPException(status_code=404, detail=f"Run with ID {run_id} not found.")
        return run_details
    except HTTPException as he:
        raise he
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/compare")
async def compare_versions(v1: str = Query(..., description="Base version"), v2: str = Query(..., description="Target version")):
    """Compares the latest evaluation runs of two pipeline versions (regression analysis)."""
    try:
        report = get_comparison_report(v1, v2)
        if "error" in report:
            raise HTTPException(status_code=404, detail=report["error"])
        return report
    except HTTPException as he:
        raise he
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/quota-usage")
async def quota_usage():
    """Returns transparent tracking of cached hits vs live external API hits."""
    try:
        db_stats = get_quota_statistics()
        return {
            "live_api_calls": QUOTA_USAGE["live_api_calls"],
            "cached_hits": QUOTA_USAGE["cached_hits"],
            "total_cached_records": db_stats["total_cached_records"]
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
